config/routes.rb
#Последний Листинг :8.1 :8.49: Обработка флажка “remember me”. app/controllers/#sessions_controller.rb  
#Листинг 3.37 :11.29 :12.20
Rails.application.routes.draw do
   resources :microposts
  

root 'static_pages#home'
  get 'sessions/new'

  get 'password_resets/new'

  get 'password_resets/edit'

resources :users
  resources :students

 #/home/sf/libr/config      Aug30   
#root 'users#index'
#/Aug30
 
#get 'articles/index'
get 'articles' => 'articles#index'

#get 'static_pages/home'
 # get 'static_pages/help'
  #get 'static_pages/about'
  #get 'static_pages/users'
  #get 'static_pages/referatHartl'
  get 'static_pages/usersallowed'
 get "/static_pages/users"
  # Sept01  get 'sessions/new'
#Листинг 5.22: Маршруты для статических страниц. config/routes.rb Листинг 7.3:
 #Articles Articles_path
#get 'Articles'    => '/articles'
get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
get 'signup'  => 'users#new'  #Листинг 5.33:Маршрут для страницы регистрации. config/#routes.rb Листинг 7.3:
                  #get 'users'  => 'static_pages#users'

# sept 10 get 'sessions/new'
#Листинг 10.1: Добавление ресурса для активаций аккаунта. config/routes.rb :11.29
resources :account_activations, only: [:edit]
resources :password_resets,     only: [:new, :create, :edit, :update]
resources :microposts,          only: [:create, :destroy]
   resources :relationships,       only: [:create, :destroy]

resources :articles
  resources :folders
  resources :reports
#Листинг 8.1
 get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
#12.15
resources :users do 
    member do
      get :following, :followers
    end
  end



#Листинг 5.33: Маршрут для страницы регистрации. config/routes.rb 
 # ! devise_for :users
 # ! devise_for :admin_users, ActiveAdmin::Devise.config
 #ActiveAdmin.routes(self)
  #  root 'users#show' был  у Мелаш
  # Example of regular route:
  get 'attach_files' => 'migration#attach_files'
  post 'attach_files' => 'migration#attach_files_action'

  post 'api/reviews_by_chapter' => 'categories#reviews_by_chapter'
  post 'api/sections_by_review' => 'categories#sections_by_review'
  post 'api/subsections_by_section' => 'categories#subsections_by_section'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
 

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable


  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/student.rb
class Student < ActiveRecord::Base
belongs_to :user

validates :user_id, presence: true

   validates :user_id, presence: true


end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
@user = User.find(params[:id])
@student = Student.find(params[:id])
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:country, :fio, :lastname, :firstname, :creditbook, :creditbooksigned, :phone, :allowed)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% provide(:title, "Edit student") %>

 <div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@student) do |f| %>
      <%##= render 'shared/error_messages', object: f.object %>     

 
<div class="field">
    <%= f.label :userid %><br>
    <%= f.text_field :user_id %>
  </div>

<div class="field">
    <%= f.label :fio %><br>
    <%= f.text_field :fio %>
  </div>

  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :fio %><br>
    <%= f.text_field :fio %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :creditbook %><br>
    <%= f.text_field :creditbook %>
  </div>
  <div class="field">
    <%= f.label :creditbooksigned %><br>
    <%= f.date_select :creditbooksigned %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :allowed %><br>
    <%= f.check_box :allowed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


  </div>
</div



>>>>>>> namefioshow-stud-master

app/views/students/_student.html.erb
<li id="student-<%= student.id %>">
  <%#= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
<span class="student">
                    <%#= link_to micropost.user.name, micropost.user %>
          <%= link_to student.user.name, student.user %></span>
     <span class="content">
          <%= student.fio %>
</span>
  
</li>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<<<<<<< HEAD
<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>
=======
<%= link_to 'Show', @student %> 
<%= link_to 'Back', students_path %>


>>>>>>> namefioshow-stud-master

app/views/students/index.html.erb
<h1>Listing students</h1>

<h1>Listing students (stud index.html.erb)</h1>


<table>
  <thead>
    <tr>

      <th>Country</th>

<th>user_id</th> 
<th>user_name</th> 
<th>user email</th>
<th>Country</th>

      <th>Fio</th>
      <th>Lastname</th>
      <th>Firstname</th>
      <th>Creditbook</th>
      <th>Creditbooksigned</th>
      <th>Phone</th>
      <th>Allowed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>

      <tr>

<td><%= student.user_id %></td> 
<td><%= student.user.name %></td> 
<td><%= student.user.email %></td>

        <td><%= student.country %></td>
        <td><%= student.fio %></td>
        <td><%= student.lastname %></td>
        <td><%= student.firstname %></td>
        <td><%= student.creditbook %></td>
        <td><%= student.creditbooksigned %></td>
        <td><%= student.phone %></td>
        <td><%= student.allowed %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>


  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Country:</strong>
  <%= @student.country %>
</p>

<p>
  <strong>Fio:</strong>
  <%= @student.fio %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @student.lastname %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @student.firstname %>
</p>

<p>
  <strong>Creditbook:</strong>
  <%= @student.creditbook %>
</p>

<p>
  <strong>Creditbooksigned:</strong>
  <%= @student.creditbooksigned %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @student.phone %>
</p>

<p>
  <strong>Allowed:</strong>
  <%= @student.allowed %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>