config/routes.rb
#Последний Листинг :8.1 :8.49: Обработка флажка “remember me”. app/controllers/#sessions_controller.rb  
#Листинг 3.37 :11.29 :12.20
Rails.application.routes.draw do
   resources :microposts
  

root 'static_pages#home'
  get 'sessions/new'

  get 'password_resets/new'

  get 'password_resets/edit'

resources :users
  resources :students

 #/home/sf/libr/config      Aug30   
#root 'users#index'
#/Aug30
 
#get 'articles/index'
get 'articles' => 'articles#index'

#get 'static_pages/home'
 # get 'static_pages/help'
  #get 'static_pages/about'
  #get 'static_pages/users'
  #get 'static_pages/referatHartl'
  get 'static_pages/usersallowed'
 get "/static_pages/users"
  # Sept01  get 'sessions/new'
#Листинг 5.22: Маршруты для статических страниц. config/routes.rb Листинг 7.3:
 #Articles Articles_path
#get 'Articles'    => '/articles'
get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
get 'signup'  => 'users#new'  #Листинг 5.33:Маршрут для страницы регистрации. config/#routes.rb Листинг 7.3:
                  #get 'users'  => 'static_pages#users'

# sept 10 get 'sessions/new'
#Листинг 10.1: Добавление ресурса для активаций аккаунта. config/routes.rb :11.29
resources :account_activations, only: [:edit]
resources :password_resets,     only: [:new, :create, :edit, :update]
resources :microposts,          only: [:create, :destroy]
   resources :relationships,       only: [:create, :destroy]

resources :articles
  resources :folders
  resources :reports
#Листинг 8.1
 get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
#12.15
resources :users do 
    member do
      get :following, :followers
    end
  end



#Листинг 5.33: Маршрут для страницы регистрации. config/routes.rb 
 # ! devise_for :users
 # ! devise_for :admin_users, ActiveAdmin::Devise.config
 #ActiveAdmin.routes(self)
  #  root 'users#show' был  у Мелаш
  # Example of regular route:
  get 'attach_files' => 'migration#attach_files'
  post 'attach_files' => 'migration#attach_files_action'

  post 'api/reviews_by_chapter' => 'categories#reviews_by_chapter'
  post 'api/sections_by_review' => 'categories#sections_by_review'
  post 'api/subsections_by_section' => 'categories#subsections_by_section'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
 

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable


  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_footer.html.erb
<!--Листинг 5.11: 
Листинг 5.24: Партиал подвала со ссылками. app/views/layouts/_footer.html.erb
 -->
<footer class="footer">
  <small>
    The <a href="http://www.libr.asf.dp.ua/">libr.asf.dp.ua</a>
    by <a href="http://www.michaelhartl.com/">Sergei Agarkov</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!--#Листинг 8.16: Изменение ссылок шаблона для вошедших пользователей. app/views/layouts/_header.html.erb :9.4- 9.36   -->

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "xgbua_min1 for students", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
 
 <% if logged_in? %>  
          <li><%= link_to "Users", users_path %></li>
<li><%= link_to "Students", students_path %></li>
      <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">           
  Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                        <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>

          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--Листинг 5.9:-app/views/layouts/_shim.html.erb -->

<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!-- #Листинг 3.32: Макет сайта учебного приложения. ЗЕЛЕНЫЙ app/views/layouts/application.html.erb 
Листинг 4.3: Шаблон сайта с хелпером full_title. ЗЕЛЕНЫЙ app/views/layouts/application.html.erb 
Листинг 5.1: Шаблон сайта с добавленными структурами. app/views/layouts/application.html.erb
Листинг 5.8: Макет сайта с партиалами для таблицы стилей и заголовка. app/views/layouts/application.html.erb
Листинг 5.12: Макет сайта с партиалом подвала. app/views/layouts/application.html.erb
:7.1 :7.25 -->
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
 <%#= debug(params) if Rails.env.development? %>

    <div class="container">
 <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
<%#= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>